set(_CATKIN_CURRENT_PACKAGE "spot_micro_joy")
set(spot_micro_joy_VERSION "0.0.0")
set(spot_micro_joy_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(spot_micro_joy_PACKAGE_FORMAT "2")
set(spot_micro_joy_BUILD_DEPENDS "joy" "rospy" "std_msgs")
set(spot_micro_joy_BUILD_EXPORT_DEPENDS "joy" "rospy" "std_msgs")
set(spot_micro_joy_BUILDTOOL_DEPENDS "catkin")
set(spot_micro_joy_BUILDTOOL_EXPORT_DEPENDS )
set(spot_micro_joy_EXEC_DEPENDS "joy" "rospy" "std_msgs")
set(spot_micro_joy_RUN_DEPENDS "joy" "rospy" "std_msgs")
set(spot_micro_joy_TEST_DEPENDS )
set(spot_micro_joy_DOC_DEPENDS )
set(spot_micro_joy_URL_WEBSITE "")
set(spot_micro_joy_URL_BUGTRACKER "")
set(spot_micro_joy_URL_REPOSITORY "")
set(spot_micro_joy_DEPRECATED "")