set(_CATKIN_CURRENT_PACKAGE "spot_micro_motion_cmd")
set(spot_micro_motion_cmd_VERSION "0.0.0")
set(spot_micro_motion_cmd_MAINTAINER "mike <mike@todo.todo>")
set(spot_micro_motion_cmd_PACKAGE_FORMAT "2")
set(spot_micro_motion_cmd_BUILD_DEPENDS "i2cpwm_board" "roscpp" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(spot_micro_motion_cmd_BUILD_EXPORT_DEPENDS "i2cpwm_board" "roscpp" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(spot_micro_motion_cmd_BUILDTOOL_DEPENDS "catkin")
set(spot_micro_motion_cmd_BUILDTOOL_EXPORT_DEPENDS )
set(spot_micro_motion_cmd_EXEC_DEPENDS "i2cpwm_board" "roscpp" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(spot_micro_motion_cmd_RUN_DEPENDS "i2cpwm_board" "roscpp" "std_msgs" "geometry_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs")
set(spot_micro_motion_cmd_TEST_DEPENDS )
set(spot_micro_motion_cmd_DOC_DEPENDS )
set(spot_micro_motion_cmd_URL_WEBSITE "")
set(spot_micro_motion_cmd_URL_BUGTRACKER "")
set(spot_micro_motion_cmd_URL_REPOSITORY "")
set(spot_micro_motion_cmd_DEPRECATED "")