set(_CATKIN_CURRENT_PACKAGE "spot_micro_rviz")
set(spot_micro_rviz_VERSION "0.0.0")
set(spot_micro_rviz_MAINTAINER "mike <michael.romanko@gmail.com>")
set(spot_micro_rviz_PACKAGE_FORMAT "2")
set(spot_micro_rviz_BUILD_DEPENDS "roscpp" "rospy")
set(spot_micro_rviz_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(spot_micro_rviz_BUILDTOOL_DEPENDS "catkin")
set(spot_micro_rviz_BUILDTOOL_EXPORT_DEPENDS )
set(spot_micro_rviz_EXEC_DEPENDS "roscpp" "rospy")
set(spot_micro_rviz_RUN_DEPENDS "roscpp" "rospy")
set(spot_micro_rviz_TEST_DEPENDS )
set(spot_micro_rviz_DOC_DEPENDS )
set(spot_micro_rviz_URL_WEBSITE "")
set(spot_micro_rviz_URL_BUGTRACKER "")
set(spot_micro_rviz_URL_REPOSITORY "")
set(spot_micro_rviz_DEPRECATED "")