set(_CATKIN_CURRENT_PACKAGE "spot_micro_keyboard_command")
set(spot_micro_keyboard_command_VERSION "0.0.0")
set(spot_micro_keyboard_command_MAINTAINER "mike <mike@todo.todo>")
set(spot_micro_keyboard_command_PACKAGE_FORMAT "2")
set(spot_micro_keyboard_command_BUILD_DEPENDS "rospy" "std_msgs" "geometry_msgs")
set(spot_micro_keyboard_command_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "geometry_msgs")
set(spot_micro_keyboard_command_BUILDTOOL_DEPENDS "catkin")
set(spot_micro_keyboard_command_BUILDTOOL_EXPORT_DEPENDS )
set(spot_micro_keyboard_command_EXEC_DEPENDS "rospy" "std_msgs" "geometry_msgs")
set(spot_micro_keyboard_command_RUN_DEPENDS "rospy" "std_msgs" "geometry_msgs")
set(spot_micro_keyboard_command_TEST_DEPENDS )
set(spot_micro_keyboard_command_DOC_DEPENDS )
set(spot_micro_keyboard_command_URL_WEBSITE "")
set(spot_micro_keyboard_command_URL_BUGTRACKER "")
set(spot_micro_keyboard_command_URL_REPOSITORY "")
set(spot_micro_keyboard_command_DEPRECATED "")