set(_CATKIN_CURRENT_PACKAGE "spot_micro_plot")
set(spot_micro_plot_VERSION "0.0.0")
set(spot_micro_plot_MAINTAINER "mike <mike@todo.todo>")
set(spot_micro_plot_PACKAGE_FORMAT "2")
set(spot_micro_plot_BUILD_DEPENDS "rospy" "std_msgs")
set(spot_micro_plot_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(spot_micro_plot_BUILDTOOL_DEPENDS "catkin")
set(spot_micro_plot_BUILDTOOL_EXPORT_DEPENDS )
set(spot_micro_plot_EXEC_DEPENDS "rospy" "std_msgs")
set(spot_micro_plot_RUN_DEPENDS "rospy" "std_msgs")
set(spot_micro_plot_TEST_DEPENDS )
set(spot_micro_plot_DOC_DEPENDS )
set(spot_micro_plot_URL_WEBSITE "")
set(spot_micro_plot_URL_BUGTRACKER "")
set(spot_micro_plot_URL_REPOSITORY "")
set(spot_micro_plot_DEPRECATED "")