set(_CATKIN_CURRENT_PACKAGE "spot_micro_launch")
set(spot_micro_launch_VERSION "0.0.0")
set(spot_micro_launch_MAINTAINER "mike <mike@todo.todo>")
set(spot_micro_launch_PACKAGE_FORMAT "2")
set(spot_micro_launch_BUILD_DEPENDS "hector_geotiff" "hector_geotiff_plugins" "hector_map_server" "hector_mapping" "hector_trajectory_server" "rviz" "tf" "tf2" "topic_tools" "rplidar_ros")
set(spot_micro_launch_BUILD_EXPORT_DEPENDS "hector_geotiff" "hector_geotiff_plugins" "hector_map_server" "hector_mapping" "hector_trajectory_server" "rviz" "tf" "tf2" "topic_tools" "rplidar_ros")
set(spot_micro_launch_BUILDTOOL_DEPENDS "catkin")
set(spot_micro_launch_BUILDTOOL_EXPORT_DEPENDS )
set(spot_micro_launch_EXEC_DEPENDS "hector_geotiff" "hector_geotiff_plugins" "hector_map_server" "hector_mapping" "hector_trajectory_server" "rviz" "tf" "tf2" "topic_tools" "rplidar_ros")
set(spot_micro_launch_RUN_DEPENDS "hector_geotiff" "hector_geotiff_plugins" "hector_map_server" "hector_mapping" "hector_trajectory_server" "rviz" "tf" "tf2" "topic_tools" "rplidar_ros")
set(spot_micro_launch_TEST_DEPENDS )
set(spot_micro_launch_DOC_DEPENDS )
set(spot_micro_launch_URL_WEBSITE "")
set(spot_micro_launch_URL_BUGTRACKER "")
set(spot_micro_launch_URL_REPOSITORY "")
set(spot_micro_launch_DEPRECATED "")